### ISSUE TITLE
(QoL?) Notification indicator on website title

### ISSUE THREAD

**Issue by cornfields74** [nilenta/rotisserie-issues-suggestions#5]
Like Discord does it, I would like a notification indicator on the title of the website as it updates; like when I get mentioned on a server or when I get an unread. Discord already does this; you can see this if you have an unread or a DM.

**Comment by alexleo2** [comment]
isnt this already a thing

**Comment by cornfields74** [comment]
No?

**Comment by lielleson** [comment]
NO!
